# Generated by Django 5.1.2 on 2024-11-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendeservicio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordendeservicio',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='orden_servicio',
        ),
        migrations.DeleteModel(
            name='Prenda',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='OrdenDeServicio',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
